title: 欢迎使用
subtitle: 个人导航站点

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: home

categories:
  - name: 常用网站
    icon: fas fa-star
    sites:
      
      
      - name: GitHub
        url: https://www.github.com
        icon: fab fa-github
        description: 代码托管平台
      
  - name: 常用网站2
    icon: fas fa-star
    sites:
      - name: GitHub
        url: https://www.github.com
        icon: fab fa-github
        description: 代码托管平台
